### ISSUE TITLE
Importer can attach mulitple files

### ISSUE THREAD

**Issue by val99erie** [curationexperts/alexandria#87]
**Acceptance Criteria**
- [ ] The CSV file accepts columns for when I want to attach 2 or more files to my work.
- [ ] The CSV column names should be the same for either a raster or vector work unless we find a reason why they need to be different.
- [ ] When I run the importer (after all the background jobs have finished), all the files will be attached in the correct order, and they will have the correct mime types.
- [ ] When I run the importer with a CSV file that is missing any of the columns that are needed to attach files successfully, the importer will give me a clear error message that tells me which columns are missing or invalid.

**Note**

At this point, don't worry about the representative file.  That will be handled in a different story.  Just get all the files attached in the correct order.

**Tasks**
- [ ] Please make sure that there is an example file under `spec/fixtures` that shows a CSV file with all the correct header names to be able to attach 2 or more files.

**Background**

We had discussed one possibility of having column names with an index that indicates the order of the files, such as `file1_filename`, `file1_mime_type`, `file2_filename`, etc.  This would be similar to how the `creator` field is handled in mahonia's importer, where the CSV file has columns for `author1_*`, `author2_*`.

**Comment by val99erie** [comment]
Need to double-check with UCSB - all the files might be inside the zip file?  If so, then we don't need additional columns in the CSV file.

**Comment by val99erie** [comment]
After re-discussion of requirements, we aren't going to do this story.  We plan to have just one zip file in CSV file for now.
